# Generated by Django 4.2.11 on 2024-10-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Názov')),
                ('start_date', models.DateField(verbose_name='Od')),
                ('end_date', models.DateField(verbose_name='Do')),
                ('description', models.TextField(blank=True, verbose_name='Popisok')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
