# Generated by Django 4.2.11 on 2024-10-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_album_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Názov')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, max_length=120, verbose_name='Popisok'),
        ),
        migrations.AlterField(
            model_name='album',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='Do'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='album',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Od'),
        ),
    ]
