# Generated by Django 4.2.11 on 2024-10-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_foto_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='name',
            field=models.CharField(max_length=15, null=True, verbose_name='Názov'),
        ),
    ]
