# Generated by Django 4.2.11 on 2024-10-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0006_remove_foto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(blank=True, max_length=120, verbose_name='Popisok'),
        ),
    ]
