# Generated by Django 4.2.11 on 2024-10-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0008_alter_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Do'),
        ),
        migrations.AlterField(
            model_name='album',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Od'),
        ),
    ]
