# Generated by Django 4.2.11 on 2024-10-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0009_alter_album_end_date_alter_album_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Názov'),
        ),
    ]
