# Generated by Django 4.2.11 on 2024-10-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0010_alter_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='img',
            field=models.ImageField(upload_to='album_imgs/%y'),
        ),
    ]
