# Generated by Django 4.2.11 on 2024-10-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0012_alter_foto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
