# Generated by Django 4.2.11 on 2024-10-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0013_foto_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='image_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
