# Generated by Django 4.2.11 on 2024-10-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0014_foto_image_date_alter_foto_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='image_date',
            new_name='image_at',
        ),
    ]
