# Generated by Django 4.2.11 on 2024-10-26 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0016_remove_foto_image_at_foto_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='foto',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
