# Generated by Django 4.2.11 on 2024-10-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0017_remove_foto_updated_at_foto_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='album',
            name='start_date',
        ),
    ]
