# Generated by Django 4.2.11 on 2024-10-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0018_remove_album_end_date_remove_album_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
    ]
