# Generated by Django 4.2.11 on 2024-10-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0021_alter_foto_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Názov'),
        ),
    ]
